<?php

declare(strict_types=1);

namespace B8im\ImShared\Protocol;

final class GroupMemberAccessError
{
    public const STATE_NOT_INITIALIZED = 'ACCESS_STATE_NOT_INITIALIZED';
    public const STATE_INVALID = 'ACCESS_STATE_INVALID';
    public const REQUEST_INVALID = 'ACCESS_SNAPSHOT_REQUEST_INVALID';
    public const SNAPSHOT_REQUIRED = 'ACCESS_SNAPSHOT_REQUIRED';
    public const SNAPSHOT_INVALID = 'ACCESS_SNAPSHOT_INVALID';
    public const SNAPSHOT_STALE = 'ACCESS_SNAPSHOT_STALE';
    public const SNAPSHOT_NOT_COMPLETED = 'ACCESS_SNAPSHOT_NOT_COMPLETED';
    public const CURSOR_INVALID = 'ACCESS_SNAPSHOT_CURSOR_INVALID';
    public const LIMIT_INVALID = 'ACCESS_SNAPSHOT_LIMIT_INVALID';
    public const VERSION_REQUIRED = 'ACCESS_VERSION_REQUIRED';
    public const VERSION_INVALID = 'ACCESS_VERSION_INVALID';
    public const VERSION_STALE = 'ACCESS_VERSION_STALE';
    public const GROUP_STATE_INVALID = 'GROUP_ACCESS_STATE_INVALID';
    public const PERIOD_INVALID = 'GROUP_ACCESS_PERIOD_INVALID';
}
